### ISSUE TITLE
Latest HTF (0.14.0.3) does not build with random-1.2

### ISSUE THREAD

**Issue by andreasabel** [skogsbaer/HTF#99]
HTF 0.14.0.3 lists for `random` the constraint >=1.0 without upper bound.  Compilation fails with random 1.2:
```
Test/Framework/QuickCheckWrapper.hs:244:16: error:
    • No instance for (Read StdGen) arising from a use of ‘readM’
    • In the expression: readM str
      In the expression:
```
```haskell
        case readM str of
          Just (_ :: Maybe (StdGen, Int))
            -> error
                 ("Your replay parameter has been produced with QuickCheck <= 2.6. It cannot be used with QuickCheck >= 2.7")
          Nothing
            -> error
                 ("Could not parse replay parameter from string " ++ show str)
```
Suggestions:
- [ ] edit the package metadata on hackage to add the upper bound
- [ ] release a version of HTF compatible with random-1.2

**Comment by andreasabel** [comment]
>     * edit the package metadata on hackage to add the upper bound

I suggest to do this, it is easy to make a revision on hackage.

If you approve and add me to http://hackage.haskell.org/package/HTF/maintainers/ I can also do this.

**Comment by skogsbaer** [comment]
There is a new version 0.14.0.4 that fixes this bug.

**Comment by skogsbaer** [comment]
btw, HTF should appear in stackage nightly soon: https://github.com/commercialhaskell/stackage/pull/5847
