### ISSUE TITLE
fails to build with ghc-8.4

### ISSUE THREAD

**Issue by juhp** [skogsbaer/HTF#66]
In stackage nightly:

```
Building library for HTF-0.13.2.2..
[ 1 of 23] Compiling Test.Framework.Colors ( Test/Framework/Colors.hs, dist/build/Test/Framework/Colors.o )
[ 2 of 23] Compiling Test.Framework.Diff ( Test/Framework/Diff.hs, dist/build/Test/Framework/Diff.o )
[ 3 of 23] Compiling Test.Framework.Location ( Test/Framework/Location.hs, dist/build/Test/Framework/Location.o )
[ 4 of 23] Compiling Test.Framework.Preprocessor ( Test/Framework/Preprocessor.hs, dist/build/Test/Framework/Preprocessor.o )

Test/Framework/Preprocessor.hs:46:1: warning: [-Wdodgy-imports]
    Module ‘Test.HUnit’ does not export ‘Location’
   |
46 | import Test.HUnit hiding (State, Location)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ 5 of 23] Compiling Test.Framework.Pretty ( Test/Framework/Pretty.hs, dist/build/Test/Framework/Pretty.o )

Test/Framework/Pretty.hs:32:18: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at Test/Framework/Pretty.hs:13:8-28
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.<>’,
                             imported from ‘Text.PrettyPrint’ at Test/Framework/Pretty.hs:22:1-23
                             (and originally defined in ‘Text.PrettyPrint.HughesPJ’)
   |
32 |         char '[' <> vcat (punctuate comma (map pretty l)) <> char ']'
   |                  ^^

Test/Framework/Pretty.hs:32:59: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at Test/Framework/Pretty.hs:13:8-28
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.<>’,
                             imported from ‘Text.PrettyPrint’ at Test/Framework/Pretty.hs:22:1-23
                             (and originally defined in ‘Text.PrettyPrint.HughesPJ’)
   |
32 |         char '[' <> vcat (punctuate comma (map pretty l)) <> char ']'
   |                                                           ^^
```

**Comment by jchia** [comment]
#67

**Comment by skogsbaer** [comment]
This problem is now fixed in master and with 0.13.2.4 on hackage. @juhp @jchia

**Comment by juhp** [comment]
Thanks a lot :+1:
