### ISSUE TITLE
HTF does not build with GHC 9.0

### ISSUE THREAD

**Issue by andreasabel** [skogsbaer/HTF#103]
Problem(s) (please extend list in case):
- [x] `regex-base` does not build with GHC 9.0 (see https://github.com/haskell-hvr/regex-base/issues/7)
- [x] `cpphs`

**Comment by andreasabel** [comment]
After the fix of `regex-*` I am now getting this error with `--allow-newer`:
```
$ cabal build -w ghc-9.0.1 --allow-newer
...
[ 9 of 24] Compiling Test.Framework.History ( Test/Framework/History.hs, /Users/abel/project/open-source/HTF/dist-newstyle/build/x86_64-osx/ghc-9.0.1/HTF-0.14.0.5/build/Test/Framework/History.o, /Users/abel/project/open-source/HTF/dist-newstyle/build/x86_64-osx/ghc-9.0.1/HTF-0.14.0.5/build/Test/Framework/History.dyn_o )

Test/Framework/History.hs:112:23: error:
    • No instance for (ToJSON SerializableTestHistory)
        arising from a use of ‘encode’
    • In the second argument of ‘($)’, namely ‘encode serHist’
      In the expression: BSL.toStrict $ encode serHist
      ...

Test/Framework/History.hs:117:10: error:
    • No instance for (FromJSON SerializableTestHistory)
        arising from a use of ‘decodeStrict’
    • In the expression: decodeStrict bs
      In the expression:
        case decodeStrict bs of
          Nothing -> Left ("could not decode JSON: " ++ show bs)
          Just !serHist
            -> let list = ...
               in
                 Right
                   (TestHistory
                      (sth_runs serHist) (createIndex list (const True))
                      (createIndex list isSuccess))
```

**Comment by skogsbaer** [comment]
@andreasabel  Do initial description also mentions cpphs. What's the problem there?

**Comment by andreasabel** [comment]
It seems that `cpphs` isn't up to `base-4.15` yet.
```
HTF$ cabal build
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: HTF-0.14.0.6 (user goal)
[__1] trying: HTF:cpphs:exe.cpphs-1.20.9.1 (dependency of HTF)
[__2] trying: HTF:cpphs:exe.polyparse-1.13 (dependency of HTF:cpphs:exe.cpphs)
[__3] next goal: HTF:cpphs:exe.base (dependency of HTF:cpphs:exe.cpphs)
[__3] rejecting: HTF:cpphs:exe.base-4.15.0.0/installed-4.15.0.0 (conflict:
HTF:cpphs:exe.polyparse => HTF:cpphs:exe.base>=4.3.1.0 && <4.15)
[__3] rejecting: HTF:cpphs:exe.base-4.14.1.0, 
...
HTF:cpphs:exe.base-3.0.3.1 (constraint from non-upgradeable package requires
installed instance)
[__3] fail (backjumping, conflict set: HTF:cpphs:exe.base,
HTF:cpphs:exe.cpphs, HTF:cpphs:exe.polyparse)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: HTF:cpphs:exe.base, HTF,
HTF:cpphs:exe.polyparse, HTF:cpphs:exe.cpphs
```

**Comment by andreasabel** [comment]
Since `polyparse` was revised just now, `HTF` builds fine on GHC 9.0.1 now!
This chapter can be closed (fingers crossed).
